# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Prateek Srivastava
tagline:
description:      Author
baseurl:          /

gems:             [jekyll-gist]

plugins:
  - jekyll-gist
